# Generated by Django 4.0.3 on 2022-04-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accountInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default=254706046810, max_length=20)),
                ('real_balance', models.FloatField(default=0)),
                ('demo_balance', models.FloatField(default=10000)),
            ],
        ),
    ]
