# Generated by Django 4.0.3 on 2022-04-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_chat_alter_accountinfomation_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chat',
            new_name='chatting',
        ),
    ]
