# Generated by Django 4.0.3 on 2022-04-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_chat_chatting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatting',
            name='message_from',
        ),
        migrations.RemoveField(
            model_name='chatting',
            name='message_to',
        ),
        migrations.AddField(
            model_name='chatting',
            name='message',
            field=models.TextField(default='nice work'),
            preserve_default=False,
        ),
    ]
